### ISSUE TITLE
archive this repo

### ISSUE THREAD

**Issue by hxrts** [cosmos/modules#118]
superseding modules:
- faucet: https://github.com/tendermint/faucet
- POA: https://github.com/allinbits/cosmos-cash
- NFT: to be released soon

**Comment by tac0turtle** [comment]
This sounds good with me.

**Comment by youngjoon-lee** [comment]
Is NFT module going to be moved to the cosmos-sdk repo? then, it's a good news to me :) May I ask about the rough timeline of it?
