### ISSUE TITLE
Is this repository abandoned? What's the status of the PoA module?

### ISSUE THREAD

**Issue by EduardoFromTheFuture** [cosmos/modules#151]
The first sentence is the [Cosmos SDK documentation](https://docs.cosmos.network/v0.50/intro/overview) says:

"The Cosmos SDK is an open-source framework for building multi-asset public Proof-of-Stake (PoS) blockchains, like the Cosmos Hub, as well as permissioned Proof-of-Authority (PoA) blockchains"

Unfortunately this is not true, as there is no official PoA module for the SDK.

I find it being developed here, but stagnated since 4 years ago.
So what's the current status on it? Why was it abandoned?

**Comment by tac0turtle** [comment]
this repo isnt used. The caption is correct, we dont offer POA out of the box but there are teams using it in production (noble)
