### ISSUE TITLE
There is no duplication check for nft ID

### ISSUE THREAD

**Issue by HaoyangLiu** [cosmos/modules#16]
The nft module doesn't check if the nft ID is duplicated. Is this an expected behavior? @marbar3778

**Comment by marbar3778** [comment]
@okwme is the author, he will be able to answer better.

**Comment by okwme** [comment]
Hi @HaoyangLiu, thanks for opening an issue!
We do a check for redundant NFT Ids here:
https://github.com/cosmos/modules/blob/master/incubator/nft/internal/types/collection.go#L50
If you're seeing different behavior than expected I'd love to hear more about it!

**Comment by okwme** [comment]
Gonna close this if there's no other problems seen
