### ISSUE TITLE
query nft supply crypto-kitties error

### ISSUE THREAD

**Issue by mengjay315** [cosmos/modules#18]
Hey,  I made an error while querying, I couldn't find a problem.

After I mint an nft, I executed the following query command ,

- `gaiacli query nft supply crypto-kitties `

- `gaiacli query nft owner cosmos1gghjut3ccd8ay0zduzj64hwre2fxs9ld75ru9p`

- `gaiacli query nft collection crypto-kitties`

- `gaiacli query nft denoms`

- `gaiacli query nft token crypto-kitties id`

 the two command queries got the error, other three commands can get the correct result.

1. `gaiacli query nft supply crypto-kitties `

2. `gaiacli query nft collection crypto-kitties`

**Error 1**

executed `gaiacli query nft supply crypto-kitties `,  get the following error:

> ERROR: cannot parse disfix JSON wrapper: invalid character '\x01' looking for beginning of value

The query method for `cliCtx.QueryWithData` has no errors and the `res= [1 0 0 0 0 0 0 0]`.

```go
// GetCmdQueryCollectionSupply queries the supply of a nft collection
func GetCmdQueryCollectionSupply(queryRoute string, cdc *codec.Codec) *cobra.Command {
         ......
         res, _, err := cliCtx.QueryWithData(fmt.Sprintf("custom/%s/supply/%s", queryRoute, denom), bz)
         if err != nil {
            return err
         }

         var out exported.NFT
         err = cdc.UnmarshalJSON(res, &out)
         if err != nil {
            return err
         }

         return cliCtx.PrintOutput(out)
      },
   }
}
```
This method `err = cdc.UnmarshalJSON(res, &out)` gives an error:  

> ERROR: cannot parse disfix JSON wrapper: invalid character '\x01' looking for beginning of value
---------------------------------------------------------------------------------------------------

**Error 2**

executed `gaiacli query nft collection crypto-kitties`, also  this method `err = cdc.UnmarshalJSON(res, &out)` gives an error:  

> ERROR: JSON encoding of interfaces require non-empty type field.

**Comment by marbar3778** [comment]
hey sorry for the delay, were you able to solve the error?
