### ISSUE TITLE
make demo apps?

### ISSUE THREAD

**Issue by okwme** [cosmos/modules#28]
Some of the modules need customization at the app level (like NFT should have a custom handler). I have a demo app for the NFT module in my personal repo, but maye it would be good for demo implementations of different modules to live here as well? or maybe they should live in `burner-chains` with a new name closer to `demo-chains`?

**Comment by marbar3778** [comment]
are you talking about the interaction with the module from a different module or the app.go file? Each module should have its own app.go for testing purposes.

**Comment by okwme** [comment]
Ah you’re right this is already done!
Closing now
