### ISSUE TITLE
fix: nft sims 

### ISSUE THREAD

**Issue by marbar3778** [cosmos/modules#29]
nft sims are failing currently. This does not pretain to the module but how an account address is call from the simulated accounts.

**Comment by usetech-llc** [comment]
We are not sure is PR https://github.com/cosmos/modules/pull/52 fixes this, but one of the tests related to simulated accounts is certainly fixed by that.

**Comment by usetech-llc** [comment]
That text fixed by PR https://github.com/cosmos/modules/pull/52: 
TestAppStateDeterminism: sim_test.go:281

**Comment by marbar3778** [comment]
@usetech-llc it seems your fix has fixed the sims, I will close this issue, thank you!!
