### ISSUE TITLE
NFT Msgs why not snake_case in JSON?

### ISSUE THREAD

**Issue by KimuraYu45z** [cosmos/modules#37]
https://github.com/cosmos/modules/blob/master/incubator/nft/internal/types/msgs.go#L16

I can understand why it is UpperCamelCase because it is a spec of golang.

However, why JSON format also be UpperCamelCase?
Using go reflection, JSON format can be specified as snake_case.

https://github.com/cosmos/cosmos-sdk/blob/master/x/bank/types/types.pb.go#L32

**Comment by marbar3778** [comment]
it seems the json tags were not set. We can go through and make these changes
